language: php

sudo: required
dist: trusty

php:
  - '7.1'

addons:
   chrome: stable

install:
   - cp .env.test .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - composer install
  - cp .env.test .env
  - php artisan key:generate
  - "mysql -e 'create database `travel`;'"
  - php artisan migrate --seed
  - php artisan passport:keys
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - phpunit -v

